-- wordlist for random project names ("<adjective> <noun>").
local M = {}
M.adjectives = {
  "obsidian", "hollow", "glacial", "velvet", "ashen", "drowned", "distant", "fractured", "dim",
  "molten", "frozen", "ember", "spectral", "derelict", "submerged", "brittle", "opaque", "luminous",
  "weightless", "decaying", "dormant", "fading", "withered", "shrouded", "veiled", "murky", "dusky",
  "somber", "mournful", "desolate", "barren", "bleak", "forlorn", "lonesome", "vacant", "abandoned",
  "ruined", "crumbling", "eroded", "weathered", "ancient", "primordial", "eternal", "endless", "boundless",
  "infinite", "vast", "immense", "cavernous", "abyssal", "fathomless", "sunken", "buried", "entombed",
  "sepulchral", "funereal", "ghostly", "phantom", "haunted", "cursed", "blighted", "withering", "rotting",
  "festering", "necrotic", "fevered", "frail", "gaunt", "skeletal", "emaciated", "pale", "leaden",
  "slate", "charcoal", "sooty", "smoky", "hazy", "foggy", "misty", "vaporous", "cloudy",
  "overcast", "sunless", "lightless", "starless", "moonless", "nocturnal", "crepuscular", "twilit", "shadowed",
  "shadowy", "umbral", "tenebrous", "stygian", "inky", "raven", "sable", "nebulous", "gloaming",
  "murmuring", "cold", "frigid", "icebound", "arctic", "polar", "wintry", "snowbound", "frostbitten",
  "rimed", "freezing", "numbing", "biting", "bitter", "harsh", "unforgiving", "relentless", "frostbound",
  "glaciated", "icy", "crystalline", "silent", "soundless", "muted", "hushed", "quiet", "still",
  "motionless", "stagnant", "lifeless", "inert", "suspended", "drifting", "floating", "sinking", "falling",
  "collapsing", "dissolving", "vanishing", "dispersing", "scattering", "broken", "shattered", "splintered", "cracked",
  "ruptured", "severed", "torn", "frayed", "worn", "tattered", "faded", "bleached", "dulled",
  "tarnished", "rusted", "corroded", "oxidized", "mossy", "lichened", "overgrown", "tangled", "knotted",
  "gnarled", "twisted", "warped", "distorted", "malformed", "grotesque", "disfigured", "crooked", "solemn",
  "grave", "austere", "stark", "grim", "dour", "sullen", "brooding", "melancholy", "wistful",
  "plaintive", "elegiac", "sorrowful", "grieving", "weeping", "aching", "yearning", "longing", "hollowed",
  "haunting", "smoldering", "charred", "scorched", "cindered", "embered", "fiery", "blazing", "searing",
  "incandescent", "glowing", "burning", "kindled", "sulfurous", "brimstone", "volcanic", "magmatic", "igneous",
  "tephra", "pyroclastic", "ashfall", "downy", "gossamer", "silken", "threadbare", "papery", "powdery",
  "dusty", "grainy", "gritty", "sandy", "chalky", "waxen", "resinous", "viscous", "syrupy",
  "oily", "slick", "damp", "dank", "clammy", "moist", "sodden", "saturated", "waterlogged",
  "brackish", "briny", "saline", "muddy", "silted", "turbid", "glimmering", "shimmering", "flickering",
  "pulsing", "throbbing", "wavering", "trembling", "quivering", "oscillating", "undulating", "phosphorescent", "iridescent",
  "opalescent", "translucent", "diaphanous", "ethereal", "gauzy", "filmy", "wan", "monolithic", "colossal",
  "titanic", "gargantuan", "towering", "looming", "oppressive", "crushing", "ponderous", "heavy", "weighty",
  "dense", "massive", "gravid", "laden", "burdened", "sunward", "forgotten", "obsolete", "disused",
  "neglected", "unkept", "moldering", "decrepit", "dilapidated", "ramshackle", "tumbledown", "weatherworn", "timeworn",
  "sunworn", "windswept", "stormbound", "tempestuous", "squalling", "gusty", "blustery", "howling", "verdigris",
  "coppered", "bronzed", "golden", "silvered", "pewter", "gunmetal", "sallow", "jaundiced", "bruised",
  "violet", "indigo", "cobalt", "ultramarine", "cyan", "teal", "emerald", "jade", "viridian",
  "ochre", "umber", "sienna", "russet", "maroon", "crimson", "carmine", "vermilion", "scarlet",
  "oxblood", "sanguine", "secret", "hidden", "arcane", "occult", "esoteric", "cryptic", "enigmatic",
  "unfathomable", "unknowable", "ineffable", "sacred", "hallowed", "consecrated", "profane", "unholy", "heretical",
  "forsaken", "godless", "ruinous", "apocalyptic", "liminal", "interstitial", "peripheral", "marginal", "outermost",
  "remote", "secluded", "isolated", "sequestered", "cloistered", "stormy", "thunderous", "lightningstruck", "rainsoaked",
  "drizzled", "sleeted", "hailstrewn", "snowdrifted", "cyclonic", "monsoonal", "windborne", "airless", "vaporized",
  "condensing", "precipitous", "cascading", "tidal", "surging", "ebbing", "receding", "narcotic", "soporific",
  "dreamlike", "hypnotic", "trancelike", "feverish", "delirious", "spectered", "hallucinatory", "oneiric", "subterranean",
  "underground", "catacombed", "tunneled", "mineshafted", "grottoed", "cavernic", "hollowing", "echoing",
}
M.nouns = {
  "drift", "cathedral", "hymn", "ruin", "tide", "ember", "glacier", "monolith", "hollow",
  "expanse", "threnody", "requiem", "static", "lattice", "vapor", "cistern", "reliquary", "undertow",
  "abyss", "void", "crypt", "catacomb", "sepulchre", "mausoleum", "ossuary", "tomb", "grave",
  "barrow", "cairn", "dolmen", "temple", "shrine", "altar", "chancel", "nave", "cloister",
  "abbey", "chapel", "basilica", "sanctuary", "tower", "spire", "belfry", "steeple", "rampart",
  "bastion", "citadel", "fortress", "keep", "battlement", "ruins", "wreckage", "rubble", "debris",
  "remnant", "relic", "vestige", "fragment", "shard", "splinter", "ocean", "sea", "gulf",
  "fjord", "sound", "strait", "channel", "estuary", "delta", "lagoon", "marsh", "mire",
  "bog", "fen", "swamp", "moor", "heath", "tarn", "mere", "lake", "river",
  "stream", "brook", "rivulet", "torrent", "cascade", "cataract", "whirlpool", "maelstrom", "eddy",
  "current", "wave", "swell", "surf", "spray", "foam", "brine", "depths", "shallows",
  "shoal", "frost", "ice", "snowfall", "blizzard", "hoarfrost", "rime", "sleet", "hailstorm",
  "permafrost", "floe", "iceberg", "crevasse", "moraine", "cornice", "avalanche", "snowdrift", "glacis",
  "icefall", "tundra", "steppe", "fog", "mist", "haze", "smog", "murk", "gloom",
  "dusk", "twilight", "gloaming", "nightfall", "midnight", "eclipse", "penumbra", "shadow", "umbra",
  "darkness", "blackness", "chasm", "storm", "tempest", "squall", "gale", "cyclone", "hurricane",
  "monsoon", "downpour", "deluge", "cloudburst", "thunder", "lightning", "wind", "gust", "breeze",
  "draft", "zephyr", "sirocco", "mistral", "tradewind", "mountain", "summit", "peak", "ridge",
  "escarpment", "cliff", "precipice", "scarp", "crag", "bluff", "valley", "gorge", "ravine",
  "canyon", "gully", "fissure", "crevice", "cleft", "rift", "cave", "cavern", "grotto",
  "den", "lair", "burrow", "warren", "tunnel", "mineshaft", "stone", "rock", "boulder",
  "slab", "obelisk", "menhir", "pillar", "column", "plinth", "ash", "cinder", "soot",
  "dust", "sand", "gravel", "scree", "silt", "clay", "loam", "flame", "blaze",
  "inferno", "pyre", "bonfire", "furnace", "forge", "kiln", "crucible", "lava", "magma",
  "caldera", "crater", "fumarole", "geyser", "brimstone", "sulfur", "obsidian", "basalt", "forest",
  "woodland", "grove", "thicket", "copse", "bramble", "undergrowth", "canopy", "bough", "branch",
  "root", "stump", "bark", "moss", "lichen", "fungus", "spore", "rot", "decay",
  "blight", "bone", "skull", "marrow", "sinew", "cadaver", "corpse", "carcass", "remains",
  "husk", "ghost", "wraith", "specter", "phantom", "apparition", "revenant", "shade", "spirit",
  "banshee", "poltergeist", "drone", "resonance", "reverberation", "echo", "murmur", "whisper", "sigh",
  "moan", "wail", "lament", "dirge", "elegy", "lullaby", "chant", "incantation", "litany",
  "psalm", "canticle", "carillon", "tolling", "noise", "hum", "throb", "pulse", "tremor",
  "shudder", "vibration", "frequency", "harmonic", "overtone", "oblivion", "eternity", "infinity", "silence",
  "stillness", "solitude", "desolation", "emptiness", "absence", "longing", "sorrow", "grief", "mourning",
  "melancholy", "despair", "dread", "unrest", "disquiet", "malaise", "ennui", "memory", "remembrance",
  "reverie", "dream", "nightmare", "vision", "trance", "slumber", "torpor", "stupor", "lantern",
  "candle", "taper", "censer", "thurible", "chalice", "urn", "sarcophagus", "shroud", "veil",
  "mantle", "cloak", "tapestry", "curtain", "drapery", "filament", "thread", "weave", "loom",
  "mirror", "glass", "prism", "lens", "crystal", "quartz", "amethyst", "garnet", "onyx",
  "jet", "engine", "mechanism", "apparatus", "contraption", "machinery", "clockwork", "gearwork", "cog",
  "ratchet", "escapement", "vessel", "hull", "derelict", "hulk", "wreck", "carrier", "barge",
  "galleon", "frigate", "schooner", "wasteland", "badlands", "barrens", "hinterland", "borderland", "wilderness",
  "desert", "dunes", "saltflat", "plain", "horizon", "skyline", "firmament", "heavens", "aether",
  "ether", "cosmos", "nebula", "starfield", "constellation", "passage", "corridor", "threshold", "gateway",
  "portal", "archway", "vault", "alcove", "recess", "niche", "procession", "cortege", "exodus",
  "pilgrimage", "wandering", "descent", "plummet", "freefall", "collapse", "ruination",
}
return M
